# api-gateway/src/main/resources/application.yml
server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: http://item-service:8081
          predicates:
            - Path=/items/**
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: http://payment-service:8083
          predicates:
            - Path=/payments/**